### ISSUE TITLE
Cannot import bartpy.samplers

### ISSUE THREAD

**Issue by dsvolk** [JakeColtman/bartpy#37]
```
from bartpy.sklearnmodel import SklearnModel
from bartpy.featureselection import SelectNullDistributionThreshold, SelectSplitProportionThreshold
from bartpy.diagnostics.features import *
```

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-97796d31de0a> in <module>
----> 1 from bartpy.sklearnmodel import SklearnModel
      2 from bartpy.featureselection import SelectNullDistributionThreshold, SelectSplitProportionThreshold
      3 from bartpy.diagnostics.features import *

~/miniconda3/envs/viz/lib/python3.7/site-packages/bartpy/sklearnmodel.py in <module>
      9 from bartpy.data import Data
     10 from bartpy.model import Model
---> 11 from bartpy.samplers.leafnode import LeafNodeSampler
     12 from bartpy.samplers.modelsampler import ModelSampler, Chain
     13 from bartpy.samplers.schedule import SampleSchedule

ModuleNotFoundError: No module named 'bartpy.samplers'

`from bartpy.samplers import *`

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-191415fb0cc7> in <module>
----> 1 from bartpy.samplers import *

ModuleNotFoundError: No module named 'bartpy.samplers'

**Comment by dsvolk** [comment]
Tried both with `pip install bartpy` version, and with 'v4' branch. Same result.

**Comment by scottrblock** [comment]
Hi @trivialfis @dsvolk, I'm getting the same error with version `0.0.2`. Any ideas how to fix?

**Comment by mkyl** [comment]
I'm also getting this issue with `0.0.2`

**Comment by watson-sam** [comment]
Any chance of this getting into the master branch / release code?

**Comment by ItamarMushkinPagaya** [comment]
I got the same issue as @eloneill (and same solution)
